version: '2.1'

services:
  bravia-server:
    image: bravia-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8001:8001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js